-- Canarias Weather & Sea V12
-- Official-source layer, warnings, tides, monetization inventory and freshness metadata.

create table if not exists public.source_status (
  source_key text primary key,
  source_name text not null,
  source_type text not null,
  last_success_at timestamptz,
  last_attempt_at timestamptz,
  status text not null default 'unknown',
  message text,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.warnings (
  id bigint generated by default as identity primary key,
  source_key text not null,
  island text,
  title text not null,
  description text,
  severity text not null default 'info',
  valid_from timestamptz,
  valid_to timestamptz,
  source_url text,
  raw jsonb,
  created_at timestamptz not null default now()
);
create index if not exists warnings_valid_idx on public.warnings(valid_from,valid_to);
alter table public.warnings enable row level security;
drop policy if exists "warnings_public_read" on public.warnings;
create policy "warnings_public_read" on public.warnings for select using (
  valid_to is null or valid_to >= now()
);
drop policy if exists "warnings_admin_all" on public.warnings;
create policy "warnings_admin_all" on public.warnings for all using (public.is_admin()) with check (public.is_admin());

create table if not exists public.tides (
  id bigint generated by default as identity primary key,
  spot_id text references public.spots(id) on delete cascade,
  event_time timestamptz not null,
  event_type text not null check(event_type in ('high','low')),
  height_m numeric,
  source_key text not null,
  raw jsonb,
  fetched_at timestamptz not null default now(),
  unique(spot_id,event_time,event_type,source_key)
);
create index if not exists tides_spot_time_idx on public.tides(spot_id,event_time);
alter table public.tides enable row level security;
drop policy if exists "tides_public_read" on public.tides;
create policy "tides_public_read" on public.tides for select using (true);
drop policy if exists "tides_admin_all" on public.tides;
create policy "tides_admin_all" on public.tides for all using (public.is_admin()) with check (public.is_admin());

create table if not exists public.monetization_slots (
  id bigint generated by default as identity primary key,
  slot_key text unique not null,
  placement text not null,
  format text not null default 'responsive',
  enabled boolean not null default false,
  provider text,
  target_url text,
  label text,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
alter table public.monetization_slots enable row level security;
drop policy if exists "monetization_public_read" on public.monetization_slots;
create policy "monetization_public_read" on public.monetization_slots for select using (enabled=true);
drop policy if exists "monetization_admin_all" on public.monetization_slots;
create policy "monetization_admin_all" on public.monetization_slots for all using (public.is_admin()) with check (public.is_admin());

insert into public.source_status(source_key,source_name,source_type,status)
values
('open_meteo','Open-Meteo','forecast','unknown'),
('aemet','AEMET OpenData','official','not_configured'),
('puertos_estado','Puertos del Estado','official_marine','not_configured')
on conflict(source_key) do nothing;

insert into public.monetization_slots(slot_key,placement,format,enabled,label)
values
('home_top','home_top','responsive',false,'Publicidad'),
('home_mid','home_mid','responsive',false,'Publicidad'),
('spot_top','spot_top','responsive',false,'Publicidad'),
('spot_bottom','spot_bottom','responsive',false,'Publicidad'),
('activity_mid','activity_mid','responsive',false,'Publicidad')
on conflict(slot_key) do nothing;
