-- Canarias Weather & Sea V14
-- Geospatial layer, map clustering support, SEO metadata and analytics events.

create extension if not exists postgis with schema extensions;

alter table public.spots
  add column if not exists location extensions.geography(point,4326);

update public.spots
set location = extensions.st_setsrid(
  extensions.st_makepoint(longitude, latitude),4326
)::extensions.geography
where location is null and latitude is not null and longitude is not null;

create index if not exists spots_location_gist on public.spots using gist(location);

create or replace function public.nearby_spots(
  lat double precision, lon double precision, radius_km double precision default 50
)
returns table(id text,name text,slug text,island text,latitude double precision,longitude double precision,distance_km double precision)
language sql stable
as $$
 select s.id,s.name,s.slug,s.island,s.latitude,s.longitude,
   extensions.st_distance(
     s.location,
     extensions.st_setsrid(extensions.st_makepoint(lon,lat),4326)::extensions.geography
   )/1000.0
 from public.spots s
 where s.published=true
   and extensions.st_dwithin(
     s.location,
     extensions.st_setsrid(extensions.st_makepoint(lon,lat),4326)::extensions.geography,
     radius_km*1000
   )
 order by s.location <-> extensions.st_setsrid(extensions.st_makepoint(lon,lat),4326)::extensions.geography;
$$;

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  spot_id text references public.spots(id) on delete set null,
  activity text,
  path text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists analytics_events_created on public.analytics_events(created_at);
alter table public.analytics_events enable row level security;

drop policy if exists "analytics_insert_public" on public.analytics_events;
create policy "analytics_insert_public" on public.analytics_events for insert with check (true);
drop policy if exists "analytics_admin_read" on public.analytics_events;
create policy "analytics_admin_read" on public.analytics_events for select using (public.is_admin());

alter table public.spots add column if not exists seo_keywords text;
alter table public.spots add column if not exists nearby_area text;
