-- FINAL PRODUCT MIGRATION
-- Consolidated operational, historical and monetization layer.

create table if not exists public.daily_spot_summary (
  id bigint generated by default as identity primary key,
  spot_id text references public.spots(id) on delete cascade,
  summary_date date not null,
  min_temp_c numeric,
  max_temp_c numeric,
  max_wind_kmh numeric,
  avg_wave_height_m numeric,
  max_wave_height_m numeric,
  dominant_wind_direction_deg numeric,
  dominant_wave_direction_deg numeric,
  water_temp_c numeric,
  best_activity text,
  best_activity_score numeric,
  source_key text not null,
  created_at timestamptz not null default now(),
  unique(spot_id,summary_date)
);
alter table public.daily_spot_summary enable row level security;
drop policy if exists "daily_summary_public_read" on public.daily_spot_summary;
create policy "daily_summary_public_read" on public.daily_spot_summary for select using (true);
drop policy if exists "daily_summary_admin_all" on public.daily_spot_summary;
create policy "daily_summary_admin_all" on public.daily_spot_summary for all using (public.is_admin()) with check (public.is_admin());

create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  email text unique not null,
  status text not null default 'active' check(status in ('active','unsubscribed')),
  created_at timestamptz not null default now()
);
alter table public.subscribers enable row level security;
drop policy if exists "subscribers_insert_public" on public.subscribers;
create policy "subscribers_insert_public" on public.subscribers for insert with check (true);
drop policy if exists "subscribers_admin_read" on public.subscribers;
create policy "subscribers_admin_read" on public.subscribers for select using (public.is_admin());

create table if not exists public.partner_links (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  url text not null,
  island text,
  spot_id text references public.spots(id) on delete set null,
  active boolean not null default true,
  label text,
  created_at timestamptz not null default now()
);
alter table public.partner_links enable row level security;
drop policy if exists "partner_links_public_read" on public.partner_links;
create policy "partner_links_public_read" on public.partner_links for select using (active=true);
drop policy if exists "partner_links_admin_all" on public.partner_links;
create policy "partner_links_admin_all" on public.partner_links for all using (public.is_admin()) with check (public.is_admin());
