-- Canarias Weather & Sea V11
-- Admin, SEO, publishing, images and operational audit layer.

alter table public.spots
  add column if not exists slug text,
  add column if not exists description text,
  add column if not exists short_description text,
  add column if not exists hero_image_path text,
  add column if not exists seo_title text,
  add column if not exists seo_description text,
  add column if not exists featured boolean not null default false,
  add column if not exists published boolean not null default true,
  add column if not exists updated_by uuid;

create unique index if not exists spots_slug_unique on public.spots(slug);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null default 'editor' check (role in ('admin','editor')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

drop policy if exists "profiles_self_read" on public.profiles;
create policy "profiles_self_read"
on public.profiles for select
using (id = auth.uid());

drop policy if exists "profiles_admin_all" on public.profiles;
create policy "profiles_admin_all"
on public.profiles for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "spots_public_read_published" on public.spots;
create policy "spots_public_read_published"
on public.spots for select
using (published = true);

drop policy if exists "spots_admin_insert" on public.spots;
create policy "spots_admin_insert"
on public.spots for insert
with check (public.is_admin());

drop policy if exists "spots_admin_update" on public.spots;
create policy "spots_admin_update"
on public.spots for update
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "spots_admin_delete" on public.spots;
create policy "spots_admin_delete"
on public.spots for delete
using (public.is_admin());

insert into storage.buckets (id, name, public)
values ('spot-images', 'spot-images', true)
on conflict (id) do nothing;

drop policy if exists "spot_images_public_read" on storage.objects;
create policy "spot_images_public_read"
on storage.objects for select
using (bucket_id = 'spot-images');

drop policy if exists "spot_images_admin_insert" on storage.objects;
create policy "spot_images_admin_insert"
on storage.objects for insert
with check (bucket_id = 'spot-images' and public.is_admin());

drop policy if exists "spot_images_admin_update" on storage.objects;
create policy "spot_images_admin_update"
on storage.objects for update
using (bucket_id = 'spot-images' and public.is_admin())
with check (bucket_id = 'spot-images' and public.is_admin());

drop policy if exists "spot_images_admin_delete" on storage.objects;
create policy "spot_images_admin_delete"
on storage.objects for delete
using (bucket_id = 'spot-images' and public.is_admin());

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor uuid references auth.users(id) on delete set null,
  action text not null,
  entity text not null,
  entity_id text,
  details jsonb,
  created_at timestamptz not null default now()
);

alter table public.audit_log enable row level security;

drop policy if exists "audit_admin_read" on public.audit_log;
create policy "audit_admin_read"
on public.audit_log for select
using (public.is_admin());

create or replace function public.log_admin_action(
  p_action text,
  p_entity text,
  p_entity_id text,
  p_details jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.audit_log(actor, action, entity, entity_id, details)
  values (auth.uid(), p_action, p_entity, p_entity_id, p_details);
end;
$$;
