-- V13: activity scoring, normalized hourly forecast, source attribution.

create table if not exists public.hourly_forecast (
  id bigint generated by default as identity primary key,
  spot_id uuid references public.spots(id) on delete cascade,
  forecast_time timestamptz not null,
  temperature_c numeric,
  wind_kmh numeric,
  wind_direction_deg numeric,
  precipitation_probability numeric,
  uv_index numeric,
  wave_height_m numeric,
  wave_direction_deg numeric,
  wave_period_s numeric,
  swell_height_m numeric,
  swell_direction_deg numeric,
  swell_period_s numeric,
  water_temp_c numeric,
  source_key text not null,
  source_kind text not null default 'model' check(source_kind in ('observation','model','official_warning')),
  fetched_at timestamptz not null default now(),
  unique(spot_id,forecast_time,source_key)
);
create index if not exists hourly_forecast_spot_time on public.hourly_forecast(spot_id,forecast_time);

create table if not exists public.activity_scores (
  id bigint generated by default as identity primary key,
  spot_id uuid references public.spots(id) on delete cascade,
  forecast_time timestamptz not null,
  activity text not null,
  score numeric not null check(score >= 0 and score <= 100),
  label text not null,
  reasons jsonb not null default '[]'::jsonb,
  source_key text not null,
  created_at timestamptz not null default now(),
  unique(spot_id,forecast_time,activity)
);
create index if not exists activity_scores_spot_time on public.activity_scores(spot_id,forecast_time);

alter table public.hourly_forecast enable row level security;
alter table public.activity_scores enable row level security;
drop policy if exists "forecast_public_read" on public.hourly_forecast;
create policy "forecast_public_read" on public.hourly_forecast for select using (true);
drop policy if exists "forecast_admin_all" on public.hourly_forecast;
create policy "forecast_admin_all" on public.hourly_forecast for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "scores_public_read" on public.activity_scores;
create policy "scores_public_read" on public.activity_scores for select using (true);
drop policy if exists "scores_admin_all" on public.activity_scores;
create policy "scores_admin_all" on public.activity_scores for all using (public.is_admin()) with check (public.is_admin());

alter table public.spots add column if not exists canonical_url text;
alter table public.spots add column if not exists region text;
